#! /usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

CATKIN_TOOLS_DOCUMENT_CONFIG_FILE="$DIR"/catkin_tools_document_config.yaml
export CATKIN_TOOLS_DOCUMENT_CONFIG_FILE

# Function to generate doucmentation of current workspace
function tue-make-documentation
{
    if [[ -n "${TUE_ENV_ROS_DISTRO}" ]] && [[ -d "${TUE_ENV_WS_DIR}" ]]
    then
        local build_tool=""
        if [[ -f "${TUE_ENV_WS_DIR}"/build/.built_by ]]
        then
            build_tool=$(cat "${TUE_ENV_WS_DIR}"/build/.built_by)
        fi
        case $build_tool in
        'catkin build')
            catkin document --workspace "${TUE_ENV_WS_DIR}" "$@"
            ;;
        '')
            catkin config --init --mkdirs --workspace "${TUE_ENV_WS_DIR}" --extend /opt/ros/"${TUE_ENV_ROS_DISTRO}" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCATKIN_ENABLE_TESTING=OFF
            catkin document --workspace "${TUE_ENV_WS_DIR}" "$@"
            touch "${TUE_ENV_WS_DIR}"/devel/.catkin # hack to allow overlaying to this ws while being empty
            ;;
        *)
            echo -e "\e$build_tool is not supported (anymore), use catkin tools\e[0m"
            return 1
            ;;
        esac
    fi
}
export -f tue-make-documentation

# Use complete function of tue-make
complete -F _tue-make tue-make-documentation

# Export docs path to open with desiserd browser
TUE_ENV_DOCS_PATH="${TUE_ENV_WS_DIR}"/docs/index.html
export TUE_ENV_DOCS_PATH
