#!/usr/bin/env python3

import json
import re
import sys
import urllib.request

url = "https://api.github.com/repos/tue-robotics/hero-dashboard/releases"
rs = json.loads(urllib.request.urlopen(url).read())

for r in rs:
    assets = (asset for asset in r["assets"] if asset["name"] == "hero-dashboard.AppImage")
    try:
        new = max(assets, key=lambda a: a["created_at"])
    except ValueError:
        continue
    url = new["browser_download_url"]
    print(r["tag_name"], url)
