#! /usr/bin/env bash
set -e

STDIN=$(cat -)

RELEASES=$(echo "$STDIN" | awk 'match($1, /^v[0-9]+.[0-9]+.[0-9]+$/) {print $0}')

readarray -t lines < <(echo "$RELEASES")
LATEST="${lines[0]}"

if [[ -n "$LATEST" ]]
then
    TAG=$(echo "$LATEST" | awk '{print $1}')
    URL=$(echo "$LATEST" | awk '{print $2}')

    if [[ -f "$IROHMS_BIN/hero_dashboard.d/$TAG" ]]
    then
        echo -e "hero-dashboard:\t\tno updates found"
    else
        echo -e "hero-dashboard:\t\tnew version $TAG found"
        mkdir -p "$IROHMS_BIN/hero_dashboard.d"
        wget "$URL" -O "$IROHMS_BIN/hero_dashboard.d/hero-dashboard.AppImage"
        chmod +x "$IROHMS_BIN/hero_dashboard.d/hero-dashboard.AppImage"
        ln -sf "$IROHMS_BIN/hero_dashboard.d/hero-dashboard.AppImage" "$IROHMS_BIN/hero_dashboard"
        touch "$IROHMS_BIN/hero_dashboard.d/$TAG"
    fi
else
    cucr-install-debug "No matching release found"
fi

set +e

