#! /usr/bin/env bash

if [[ ! -v TUE_ENV_ROS_VERSION && -v TUE_ROS_VERSION ]]
then
    TUE_ENV_ROS_VERSION=${TUE_ROS_VERSION}
    >&2 echo "Change the config of your environment to use 'TUE_ENV_ROS_VERSION' instead of 'TUE_ROS_VERSION'"
fi
if [[ "${TUE_ENV_ROS_VERSION}" -eq 1 ]]
then
    alias swri="rosrun swri_console swri_console"
else
    alias swri="ros2 run swri_console swri_console"
fi
