#! /usr/bin/env bash

# Robot real
export ROBOT_REAL=true

# Logout global git user on robot
function git-logout
{
    git config --global --get user.name > /dev/null && git config --global --remove user
}

# If this is run the first since this computer was started, remove
# the user details (forcing the user to 'log-in')
if [[ ! -f /tmp/git-removed-user-details ]]
then
    touch /tmp/git-removed-user-details
    git-logout
fi
