#!/usr/bin/env python3

import json
import re
import sys
import urllib.request

v = sys.argv[1] if len(sys.argv) == 2 else exit("no version specified")

url = "https://api.github.com/repos/tue-robotics/dashboard/releases"
rs = json.loads(urllib.request.urlopen(url).read())

for r in rs:
    assets = (asset for asset in r["assets"] if asset_re.match(asset["name"]))
    try:
        new = max(assets, key=lambda a: a["created_at"])
    except ValueError:
        continue
    url = new["browser_download_url"]
    print(r["tag_name"], url)
