#! /usr/bin/env bash

# Load Toyota version variables
while read -r line
do
    eval "export $line"
done < /etc/opt/tmc/robot/version

alias hero-sync-ubuntu-ntp="sudo ntpdate ntp.ubuntu.com"

if [[ "${TUE_ROS_USE_IP}" == "true" ]]
then
    unset ROS_HOSTNAME
    export ROS_IP=192.168.44.51
    export ROS_MASTER_URI=http://192.168.44.51:11311
fi
