#! /usr/bin/env bash

# Load Toyota version variables
while read -r line
do
    eval "export $line"
done < /etc/opt/tmc/robot/version

alias hero-sync-ubuntu-ntp="sudo ntpdate ntp.ubuntu.com"

function _vbox_sleep
{
    sleep 1;
    local i
    i=0
    while [[ $i -lt 30 ]]
    do
        if ! lsmod | grep -q vbox
        then
            echo "All vbox modules stopped"
            return 0
        fi
        sleep 0.5
        i=$((i+1))
    done
    echo "Not all vbox modules stopped"
}

function _stop_vbox_services
{
    sudo systemctl stop hero1-speech5-windows-speech.service 2>/dev/null
    sudo systemctl stop hero1-speech4-vboxweb-service.service 2>/dev/null
    sudo systemctl stop hero1-speech3-vboxdrv.service 2>/dev/null
    sudo systemctl stop hero1-speech2-vboxballoonctrl-service.service 2>/dev/null
    sudo systemctl stop hero1-speech1-vboxautostart-service.service 2>/dev/null
    sudo systemctl stop hero1-demo-speech5-windows-speech.service 2>/dev/null
    sudo systemctl stop hero1-demo-speech4-vboxweb-service.service 2>/dev/null
    sudo systemctl stop hero1-demo-speech3-vboxdrv.service 2>/dev/null
    sudo systemctl stop hero1-demo-speech2-vboxballoonctrl-service.service 2>/dev/null
    sudo systemctl stop hero1-demo-speech1-vboxautostart-service.service 2>/dev/null
}

function hero-reboot
{
    _stop_vbox_services
    _vbox_sleep
    sudo reboot
}

function hero-shutdown
{
    _stop_vbox_services
    _vbox_sleep
    sudo shutdown -h -t 0
}

