#! /usr/bin/env bash

alias hero2-test-rgbd-shm="rosrun rgbd rgbd_test_client_shm --headless test:=/hero/head_rgbd_sensor/rgbd"

unset ROS_HOSTNAME
export ROS_IP=192.168.44.52
export ROS_MASTER_URI=http://192.168.44.51:11311
