#! /usr/bin/env bash

# Don't delete git user details on own computer
touch /tmp/git-removed-user-details

bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'
bind '"\e[C": forward-char'
bind '"\e[D": backward-char'

function sb
{
    # shellcheck disable=SC1090
    source ~/.bashrc
}

alias ag='ag -fi'

alias ccat='pygmentize -g -O style=colorful'
