#! /usr/bin/env bash

if [[ $- == *i* ]]
then
    bind '"\e[A": history-search-backward'
    bind '"\e[B": history-search-forward'
    bind '"\e[C": forward-char'
    bind '"\e[D": backward-char'
fi

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

function sb
{
    # shellcheck disable=SC1090
    source ~/.bashrc
}

alias ag='ag -f'

alias ccat='pygmentize -g -O style=colorful'

alias ssh-del-cm='rm ~/.ssh/controlmasters/*'

function update-apt
{
    if [[ ! -f /tmp/tue_get_apt_get_updated ]]
    then
        sudo apt-get update
    fi
    touch /tmp/tue_get_apt_get_updated
    sudo apt-get upgrade --with-new-pkgs --autoremove
}

function remove-old-snaps
{
    # shellcheck disable=SC2162
    LANG=en_US.UTF-8 snap list --all | awk '/disabled/{print $1, $3}' |
    while read snapname revision
    do
        echo "Removing ${snapname} (${revision})"
        sudo snap remove "${snapname}" --revision="${revision}"
    done
}

function update-snap
{
    sudo snap refresh
    remove-old-snaps
}

