#!/usr/bin/env python

import sys
import urllib2
import json
import re

url = 'https://api.github.com/repos/tue-robotics/hero-display/releases'
rs = json.loads(urllib2.urlopen(url).read())

for r in rs:
    assets = (asset for asset in r['assets'] if asset['name'] == "hero-display.AppImage")
    try:
        new = max(assets, key=lambda a: a['created_at'])
    except ValueError:
        continue
    url = new['browser_download_url']
    print r['tag_name'], url
