#! /usr/bin/env bash
set -e

STDIN=$(cat -)

RELEASES=$(echo "$STDIN" | awk 'match($1, /^v[0-9]+.[0-9]+.[0-9]+$/) {print $0}')

readarray -t lines < <(echo "$RELEASES")
LATEST="${lines[0]}"

if [[ -n "$LATEST" ]]
then
    TAG=$(echo "$LATEST" | awk '{print $1}')
    URL=$(echo "$LATEST" | awk '{print $2}')

    if [[ -f "$TUE_BIN/hero_display.d/$TAG" ]]
    then
        tue-install-echo "no updates found"
    else
        tue-install-echo "new version $TAG found"
        mkdir -p "$TUE_BIN/hero_display.d"
        wget "$URL" -O "$TUE_BIN/hero_display.d/hero-display.AppImage"
        chmod +x "$TUE_BIN/hero_display.d/hero-display.AppImage"
        ln -sf "$TUE_BIN/hero_display.d/hero-display.AppImage" "$TUE_BIN/hero_display"
        touch "$TUE_BIN/hero_display.d/$TAG"
    fi
else
    tue-install-debug "No matching release found"
fi

set +e
