#! /usr/bin/env bash

alias local-core='export ROS_MASTER_URI=http://localhost:11311'
function hostname-core
{
    # shellcheck disable=SC2155
    export ROS_MASTER_URI=http://$(hostname).local:11311
}

####################
#
# Robocup
#
####################

alias topic-monitor='rosrun robot_launch_files topic_monitor */scan */rgbd */joint_states */base/measurements'

alias scores='scp amigo@athome10.local:/home/amigo/database/per_challenge/scores.html /tmp/scores.html && google-chrome /tmp/scores.html'
