#! /usr/bin/env bash

####################
#
# Robocup
#
####################

alias topic-monitor='rosrun robot_launch_files topic_monitor */scan */rgbd */joint_states */base/measurements'

alias scores='scp amigo@athome10.local:/home/amigo/database/per_challenge/scores.html /tmp/scores.html && google-chrome /tmp/scores.html'
