#! /usr/bin/env bash

####################
#
# SSH
#
####################
alias sshhero1='until ssh -qAo ConnectTimeout=1 administrator@hero1.local; do echo waiting for hero1 to come online...; sleep 2; done'
alias sshhero2='until ssh -qAo ConnectTimeout=1 amigo@hero2.local; do echo waiting for hero2 to come online...; sleep 2; done'
alias hero-copy-my-id="ssh-copy-id administrator@hero1.local; ssh-copy-id amigo@hero2.local"
