#! /usr/bin/env bash

if [ -z "$TUE_ROS_DISTRO" ]
then
    echo -e "\e[31;1m[ros] TUE_ROS_DISTRO was not set\e[0m"
    return 1
fi

# shellcheck disable=SC1090
if [ -f "$TUE_DEV_DIR"/devel/setup.bash ]
then
    source "$TUE_DEV_DIR"/devel/setup.bash

elif [ -f "$TUE_SYSTEM_DIR"/devel/setup.bash ]
then
    echo -e "\e[33;1m[ros] dev workspace not found, sourcing system workspace\e[0m"
    source "$TUE_SYSTEM_DIR"/devel/setup.bash

else
    echo -e "\e[33;1m[ros] dev and system workspaces not found, sourcing /opt/ros\e[0m"
    source /opt/ros/"$TUE_ROS_DISTRO"/setup.bash
fi

# Set ROSCONSOLE_FORMAT
# shellcheck disable=SC2016
ROSCONSOLE_FORMAT='[${severity}][${node}][${time}]: ${message}'
export ROSCONSOLE_FORMAT
