#! /usr/bin/env bash

if [ -z "$TUE_ROS_DISTRO" ]
then
    echo "[tue ros setup] TUE_ROS_DISTRO was not set"
    return 1
fi

unset CMAKE_PREFIX_PATH
# shellcheck disable=SC1090
source "$TUE_DEV_DIR"/devel/setup.bash

# shellcheck disable=SC2016
ROSCONSOLE_FORMAT='[${severity}][${node}][${time}]: ${message}'
export ROSCONSOLE_FORMAT
