#! /usr/bin/env bash

if [[ -z "${TUE_ENV_ROS_DISTRO}" ]]
then
    >&2 echo -e "\e[31;1m[ros1] TUE_ENV_ROS_DISTRO was not set.\e[0m"
    return 1
fi

if [[ -f "${TUE_ENV_WS_DIR}"/devel/setup.bash ]]
then
    # shellcheck disable=SC1091
    source "${TUE_ENV_WS_DIR}"/devel/setup.bash
else
    >&2 echo -e "\e[33;1m[ros] system workspaces not found, sourcing /opt/ros\e[0m"
    # shellcheck disable=SC1090
    source /opt/ros/"${TUE_ENV_ROS_DISTRO}"/setup.bash
fi

# Set ROSCONSOLE_FORMAT
# shellcheck disable=SC2016
ROSCONSOLE_FORMAT='[${severity}][${node}][${time}]: ${message}'
export ROSCONSOLE_FORMAT

DISABLE_ROS1_EOL_WARNINGS=true
export DISABLE_ROS1_EOL_WARNINGS
