#! /usr/bin/env bash

# TODO(anyone): remove when tue-env is updated to new variable names
[[ -v TUE_ENV_WS_DIR || ! -v TUE_WS_DIR ]] || TUE_ENV_WS_DIR=${TUE_WS_DIR}

export GAZEBO_PLUGIN_PATH=~/${TUE_ENV_WS_DIR}/devel/lib:${GAZEBO_PLUGIN_PATH}

export GAZEBO_MODEL_PATH=~/${TUE_ENV_WS_DIR}/src/tue_gazebo_models/database:${GAZEBO_MODEL_PATH}

export GAZEBO_RESOURCE_PATH=~/${TUE_ENV_WS_DIR}/src/tue_gazebo_models/database:${GAZEBO_RESOURCE_PATH}
