#! /usr/bin/env bash
# shellcheck disable=SC2034

function _any-core
{
    export ROS_MASTER_URI="http://$1:11311"
}

function _robot-core
{
    _any-core "$1.local"
}

alias local-core='_any-core localhost'

####################
#
# ROS_HOSTNAME
#
####################

# Append '.local' to hostname for local resolving of hostnames
ROS_HOSTNAME=$(hostname).local
export ROS_HOSTNAME
