#! /usr/bin/env bash
# shellcheck disable=SC2034

####################
#
# git PS1
#
####################

GIT_PS1_SHOWDIRTYSTATE=1
GIT_PS1_SHOWSTASHSTATE=1
GIT_PS1_SHOWUNTRACKEDFILES=1
# Explicitly unset color (default anyhow). Use 1 to set it.
GIT_PS1_SHOWCOLORHINTS=1
GIT_PS1_DESCRIBE_STYLE="branch"
GIT_PS1_SHOWUPSTREAM="auto git"

function _ROS_MASTER_NAME {
    [[ "${TUE_ENV_ROS_VERSION}" -ne 1 ]] && return
    # shellcheck disable=SC2001
    ROS_MASTER=$(echo "${ROS_MASTER_URI}" | sed 's#http://\(.*\):.*#\1#')
    if [ "${ROS_MASTER}" == "localhost" ] || [ "${ROBOT_REAL}" == "true" ]; then
        echo ""
    else
        echo "(${ROS_MASTER}-core) "
    fi
}

function _ROS2_DISCOVERY {
    [[ "${TUE_ENV_ROS_VERSION}" -ne 2 ]] && return
    # shellcheck disable=SC2153
    local ros_domain_id=${ROS_DOMAIN_ID}
    [[ -n "${ros_domain_id}" ]] || ros_domain_id=0 # default
    # shellcheck disable=SC2153
    local ros_automatic_discovery_range=${ROS_AUTOMATIC_DISCOVERY_RANGE}
    [[ -n "${ros_automatic_discovery_range}" ]] || ros_automatic_discovery_range="SUBNET" # default
    if [ "${ros_automatic_discovery_range}" == "LOCALHOST" ] || [ "${ros_automatic_discovery_range}" == "SYSTEM_DEFAULT" ]
    then
        echo ""
    else
        echo "(${ros_domain_id}:${ros_automatic_discovery_range}) "
    fi
}

function _VIRTUAL_ENV_NAME {
    local virtual_env_name
    { [[ -v VIRTUAL_ENV_PROMPT ]] && virtual_env_name="${VIRTUAL_ENV_PROMPT}" ; } || virtual_env_name=$(basename "${VIRTUAL_ENV}")
    [[ -n ${virtual_env_name} ]] && echo "(${virtual_env_name}) " || echo ""
}

# shellcheck disable=SC2154
PS1='$(_VIRTUAL_ENV_NAME)[\[\e[01;34m\]\w\[\e[00m\]]$(__git_ps1)\n'\
'$(_ROS_MASTER_NAME)$(_ROS2_DISCOVERY)${debian_chroot:+($debian_chroot)}\[\e[01;32m\]\u@\h\[\e[00m\] \$ '
# shellcheck disable=SC2016
_OLD_VIRTUAL_PS1='[\[\e[01;34m\]\w\[\e[00m\]]$(__git_ps1)\n'\
'$(_ROS_MASTER_NAME)$(_ROS2_DISCOVERY)${debian_chroot:+($debian_chroot)}\[\e[01;32m\]\u@\h\[\e[00m\] \$ '
