#! /usr/bin/env bash

function qtcreator
{
    /opt/Qt/Tools/QtCreator/bin/qtcreator.sh
}

# TODO(anyone): remove when tue-env is updated to new variable names
if [[ ! -v TUE_ENV_ROS_VERSION && -v TUE_ROS_VERSION ]]
then
    TUE_ENV_ROS_VERSION=${TUE_ROS_VERSION}
    >&2 echo -e "\e[33;1m[qtcreator] Change the config of your environment to use 'TUE_ENV_ROS_DISTRO' instead of 'TUE_ROS_DISTRO'.\e[0m"
fi

# TODO(anyone): remove when tue-env is updated to new variable names
[[ -v TUE_ENV_WS_DIR || ! -v TUE_WS_DIR ]] || TUE_ENV_WS_DIR=${TUE_WS_DIR}

if [[ "${TUE_ENV_ROS_VERSION}" -eq 1 ]]
then
    # Make sure packages can be build by QT
    CURRENT_CMAKE_BUILD_DIR=$(catkin locate --workspace "${TUE_ENV_WS_DIR}" --build 2>/dev/null)
else
    CURRENT_CMAKE_BUILD_DIR="${TUE_ENV_WS_DIR}"/build
fi

export CURRENT_CMAKE_BUILD_DIR
